name: CraftBan
version: 2.0
main:  io.github.zachohara.bukkit.craftban.CraftBanPlugin
depend: [SimplePlugin]
description: A crafting and smelting restriction tool
author: Zach Ohara
commands:
  bancraft:
    description: Ban or unban the given material from being crafted
    usage: /bancraft <material>
  bansmelt:
    description: Ban or unban the given material from being smelted into something else
    usage: /bansmelt <material>
  banfuel:
    description: Ban or unban the given material from being used as fuel for smelting
    usage: /banfuel <material>
  bannedcraftlist:
    description: Get the list of materials that are banned form being crafted
    usage: /bannedcraftlist
    aliases: [bancraftlist, craftbanlist]
  bannedsmeltlist:
    description: Get the list of materials that are banned form being smelted into something else
    usage: /bannedsmelttlist
    aliases: [bansmeltlist, smeltbanlist]
  bannedfuellist:
    description: Get the list of materials that are banned form being used as fuel for smelting
    usage: /bannedfuellist
    aliases: [banfuellist, fuelbanlist]
