name: CraftBan
version: 0.3
main:  io.github.zachohara.bukkit.craftban.CraftBanPlugin
depend: [BukkitCommon]
description: A crafting and smelting restriction tool
author: Zach Ohara
commands:
  bancraft:
    description: Ban the given material from being crafted
    usage: /bancraft <material>
  bansmelt:
    description: Ban the given material from being smelted into something else
    usage: /bansmelt <material>
  banfuel:
    description: Ban the given material from being used as fuel for smelting
    usage: /banfuel <material>
  bannedcraftlist:
    description: Get the list of materials that are banned form being crafted
    usage: /bannedcraftlist
    aliases: [bancraftlist]
  bannedsmeltlist:
    description: Get the list of materials that are banned form being smelted into something else
    usage: /bannedsmelttlist
    aliases: [bansmeltlist]
  bannedfuellist:
    description: Get the list of materials that are banned form being used as fuel for smelting
    usage: /bannedfuellist
    aliases: [banfuellist]
